version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB_URL=mongodb://mongo:27017/devlife
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=sk-XXXXXXXXXXXXXXXX
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=devlife;Username=devuser;Password=devpass

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: devlife
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mongo-data:
  pgdata:
