services:
  devlife-api:
    build:
      context: .
      dockerfile: DevLife.APIproj/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=sk-XXXXXXXXXXXX
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - DATABASE_URL=Host=postgres;Database=devlife;Username=devuser;Password=devpass
      - MONGODB_URL=mongodb://mongo:27017/devlife
      - REDIS_URL=redis:6379
    depends_on:
      - postgres
      - mongo
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: devlife
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodata:
