version: '3.8'

services:
  devlife-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devlife-api
    ports:
      - "5000:80"
    depends_on:
      - postgres
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: devlife-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devlife
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
